### ISSUE TITLE
Write capability

### ISSUE THREAD

**Issue by posix4e** [lyft/dynamodb-hive-serde#4]
Can I write out exports this way?

**Comment by posix4e** [comment]
create external table dynamodb(fakecol1 bigint, fakecol2 string, fakecol3 string, fakecol4 string, fakecol5 bigint, fakecol6 lstring, fakecol7 bigint, fakecol8 bigint, fakecol9 bigint, fakecol10 bigint, fakecol11 bigint, fakecol12 string, fakecol13 string) ROW FORMAT SERDE 'com.lyft.hive.serde.DynamoDbSerDe' LOCATION 's3://alexasdf/serde';

gets
1.us-west-2.compute.internal:8088/taskdetails.jsp?jobid=job_1444240606448_0042&tipid=task_1444240606448_0042_r_000000
-----
Diagnostic Messages for this Task:
Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":30,"_col1":"20150828_092318_0b10.tif","_col2":"s3","_col3":"39f674e1c7eb6abd0fa6d547b9ccf57e","_col4":793193,"_col5":"{\"type\":\"Polygon\",\"coordinates\":[[[\"107.74267620449625\",\"38.20273014635555\"],[\"107.80577684786502\",\"38.163836335233384\"],[\"107.84369359085983\",\"38.20222516203852\"],[\"107.78049077973573\",\"38.24107155249924\"],[\"107.74267620449625\",\"38.20273014635555\"]]]}","_col6":126778515,"_col7":1440753798000,"_col8":126778515,"_col9":74144,"_col10":1443637104000,"_col11":"","_col12":""}}
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:265)
        at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:455)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:171)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:166)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":30,"_col1":"20150828_092318_0b10.tif","_col2":"s3","_col3":"39f674e1c7eb6abd0fa6d547b9ccf57e","_col4":793193,"_col5":"{\"type\":\"Polygon\",\"coordinates\":[[[\"107.74267620449625\",\"38.20273014635555\"],[\"107.80577684786502\",\"38.163836335233384\"],[\"107.84369359085983\",\"38.20222516203852\"],[\"107.78049077973573\",\"38.24107155249924\"],[\"107.74267620449625\",\"38.20273014635555\"]]]}","_col6":126778515,"_col7":1440753798000,"_col8":126778515,"_col9":74144,"_col10":1443637104000,"_col11":"","_col12":""}}
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:253)
        ... 7 more
Caused by: java.lang.UnsupportedOperationException: DynamoDb SerDe doesn't support the serialize() method
        at com.lyft.hive.serde.DynamoDbSerDe.serialize(DynamoDbSerDe.java:259)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:692)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
        at org.apache.hadoop.hive.ql.exec.LimitOperator.processOp(LimitOperator.java:51)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
        at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:84)
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:244)
        ... 7 more

**Comment by posix4e** [comment]
It gets 
----
Diagnostic Messages for this Task:
Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":30,"_col1":"20150828_092318_0b10.tif","_col2":"s3","_col3":"39f674e1c7eb6abd0fa6d547b9ccf57e","_col4":793193,"_col5":"{\"type\":\"Polygon\",\"coordinates\":[[[\"107.74267620449625\",\"38.20273014635555\"],[\"107.80577684786502\",\"38.163836335233384\"],[\"107.84369359085983\",\"38.20222516203852\"],[\"107.78049077973573\",\"38.24107155249924\"],[\"107.74267620449625\",\"38.20273014635555\"]]]}","_col6":126778515,"_col7":1440753798000,"_col8":126778515,"_col9":74144,"_col10":1443637104000,"_col11":"","_col12":""}}
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:265)
        at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:455)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:171)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:166)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":30,"_col1":"20150828_092318_0b10.tif","_col2":"s3","_col3":"39f674e1c7eb6abd0fa6d547b9ccf57e","_col4":793193,"_col5":"{\"type\":\"Polygon\",\"coordinates\":[[[\"107.74267620449625\",\"38.20273014635555\"],[\"107.80577684786502\",\"38.163836335233384\"],[\"107.84369359085983\",\"38.20222516203852\"],[\"107.78049077973573\",\"38.24107155249924\"],[\"107.74267620449625\",\"38.20273014635555\"]]]}","_col6":126778515,"_col7":1440753798000,"_col8":126778515,"_col9":74144,"_col10":1443637104000,"_col11":"","_col12":""}}
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:253)
        ... 7 more
Caused by: java.lang.UnsupportedOperationException: DynamoDb SerDe doesn't support the serialize() method
        at com.lyft.hive.serde.DynamoDbSerDe.serialize(DynamoDbSerDe.java:259)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:692)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
        at org.apache.hadoop.hive.ql.exec.LimitOperator.processOp(LimitOperator.java:51)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
        at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:84)
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:244)

**Comment by ewalker11** [comment]
Hi @posix4e, sorry for the extended delay in responding! This serde doesn't support serialize (I guess it's just a "de"), but it's definitely functionality that could be added. Can you give me a bit more context around your usecase? Are you transforming archive files and then re-loading them into DynamoDB?

**Comment by bhavin1223** [comment]
Hey @ewalker11, Does current version of serde support serialize?
